apiVersion: apps/v1                                                             
kind: Deployment                                                                
metadata:                                                                       
  name: kubevirt-cloud-controller-manager
  namespace: default
spec:                                                                           
  template:                                                                     
    spec:                                                                       
      volumes:                                                               
      - secret:
          secretName: kubeconfig
          items:
            - key: kubeconfig
              path: value
        name: kubeconfig
